version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: selaski-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: selaski
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: